[2022-10-17 22:23:03,655: INFO: stage_01_get_data]: 
********************
[2022-10-17 22:23:03,656: INFO: stage_01_get_data]: >>>>> stage stage 01 get data started <<<<<
[2022-10-17 22:23:03,656: ERROR: stage_01_get_data]: 'Namespace' object has no attribute 'params'
Traceback (most recent call last):
  File "D:\MLops\DVC-NLP\src\stage_01_get_data.py", line 32, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
AttributeError: 'Namespace' object has no attribute 'params'
[2022-10-17 22:23:52,140: INFO: stage_01_get_data]: 
********************
[2022-10-17 22:23:52,140: INFO: stage_01_get_data]: >>>>> stage stage 01 get data started <<<<<
[2022-10-17 22:23:52,145: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-10-17 22:23:52,185: INFO: stage_01_get_data]: >>>>> stage stage 01 get data completed!<<<<<

[2022-10-17 22:35:17,709: INFO: stage_01_get_data]: 
********************
[2022-10-17 22:35:17,709: INFO: stage_01_get_data]: >>>>> stage stage 01 get data started <<<<<
[2022-10-17 22:35:17,715: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-10-17 22:35:17,715: ERROR: stage_01_get_data]: 'source_download_dir'
Traceback (most recent call last):
  File "D:\MLops\DVC-NLP\src\stage_01_get_data.py", line 37, in <module>
    main(config_path=parsed_args.config)
  File "D:\MLops\DVC-NLP\src\stage_01_get_data.py", line 23, in main
    local_data_dir = config["source_download_dir"]["data_dir"]
KeyError: 'source_download_dir'
[2022-10-17 22:38:36,654: INFO: stage_01_get_data]: 
********************
[2022-10-17 22:38:36,655: INFO: stage_01_get_data]: >>>>> stage stage 01 get data started <<<<<
[2022-10-17 22:38:36,662: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-10-17 22:38:36,663: INFO: common]: created directory at: data
[2022-10-17 22:38:36,665: INFO: stage_01_get_data]: >>>>> stage stage 01 get data completed!<<<<<

[2022-10-17 22:42:48,378: INFO: stage_01_get_data]: 
********************
[2022-10-17 22:42:48,379: INFO: stage_01_get_data]: >>>>> stage stage 01 get data started <<<<<
[2022-10-17 22:42:48,385: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-10-17 22:42:48,386: INFO: common]: created directory at: data
[2022-10-17 22:42:48,386: INFO: stage_01_get_data]: >>>>> stage stage 01 get data completed!<<<<<

[2022-10-17 22:48:00,747: INFO: stage_01_get_data]: 
********************
[2022-10-17 22:48:00,747: INFO: stage_01_get_data]: >>>>> stage stage 01 get data started <<<<<
[2022-10-17 22:48:00,756: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-10-17 22:48:00,757: INFO: common]: created directory at: data
[2022-10-17 22:48:00,758: INFO: stage_01_get_data]: Download started
[2022-10-17 22:48:01,715: ERROR: stage_01_get_data]: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "D:\MLops\DVC-NLP\src\stage_01_get_data.py", line 44, in <module>
    main(config_path=parsed_args.config)
  File "D:\MLops\DVC-NLP\src\stage_01_get_data.py", line 31, in main
    filename, headers = req.urlretrieve(source_data_url,local_data_filepath)
  File "D:\MLops\DVC-NLP\env\lib\urllib\request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "D:\MLops\DVC-NLP\env\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "D:\MLops\DVC-NLP\env\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "D:\MLops\DVC-NLP\env\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "D:\MLops\DVC-NLP\env\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "D:\MLops\DVC-NLP\env\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "D:\MLops\DVC-NLP\env\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2022-10-18 11:40:44,063: INFO: stage_01_get_data]: 
********************
[2022-10-18 11:40:44,063: INFO: stage_01_get_data]: >>>>> stage stage 01 get data started <<<<<
[2022-10-18 11:40:44,067: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-10-18 11:40:44,068: INFO: common]: created directory at: data
[2022-10-18 11:40:44,068: INFO: stage_01_get_data]: Download started
[2022-10-18 11:40:44,665: ERROR: stage_01_get_data]: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "d:\MLops\DVC-NLP\src\stage_01_get_data.py", line 44, in <module>
    main(config_path=parsed_args.config)
  File "d:\MLops\DVC-NLP\src\stage_01_get_data.py", line 31, in main
    filename, headers = req.urlretrieve(source_data_url, local_data_filepath)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
[2022-10-18 11:42:42,405: INFO: stage_01_get_data]: 
********************
[2022-10-18 11:42:42,405: INFO: stage_01_get_data]: >>>>> stage stage 01 get data started <<<<<
[2022-10-18 11:42:42,408: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-10-18 11:42:42,408: INFO: common]: created directory at: data
[2022-10-18 11:42:42,409: INFO: stage_01_get_data]: Download started
[2022-10-18 11:42:43,004: ERROR: stage_01_get_data]: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "d:\MLops\DVC-NLP\src\stage_01_get_data.py", line 44, in <module>
    main(config_path=parsed_args.config)
  File "d:\MLops\DVC-NLP\src\stage_01_get_data.py", line 31, in main
    filename, headers = req.urlretrieve(source_data_url, local_data_filepath)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
[2022-10-18 11:44:56,625: INFO: stage_01_get_data]: 
********************
[2022-10-18 11:44:56,625: INFO: stage_01_get_data]: >>>>> stage stage 01 get data started <<<<<
[2022-10-18 11:44:56,627: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-10-18 11:44:56,627: INFO: common]: created directory at: data
[2022-10-18 11:44:56,627: INFO: stage_01_get_data]: Download started
[2022-10-18 11:44:56,629: ERROR: stage_01_get_data]: <urlopen error unknown url type: s3>
Traceback (most recent call last):
  File "d:\MLops\DVC-NLP\src\stage_01_get_data.py", line 44, in <module>
    main(config_path=parsed_args.config)
  File "d:\MLops\DVC-NLP\src\stage_01_get_data.py", line 31, in main
    filename, headers = req.urlretrieve(source_data_url, local_data_filepath)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 539, in _open
    return self._call_chain(self.handle_open, 'unknown',
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 1417, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: s3>
[2022-10-18 11:45:02,629: INFO: stage_01_get_data]: 
********************
[2022-10-18 11:45:02,629: INFO: stage_01_get_data]: >>>>> stage stage 01 get data started <<<<<
[2022-10-18 11:45:02,632: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-10-18 11:45:02,632: INFO: common]: created directory at: data
[2022-10-18 11:45:02,632: INFO: stage_01_get_data]: Download started
[2022-10-18 11:45:02,633: ERROR: stage_01_get_data]: <urlopen error unknown url type: s3>
Traceback (most recent call last):
  File "d:\MLops\DVC-NLP\src\stage_01_get_data.py", line 44, in <module>
    main(config_path=parsed_args.config)
  File "d:\MLops\DVC-NLP\src\stage_01_get_data.py", line 31, in main
    filename, headers = req.urlretrieve(source_data_url, local_data_filepath)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 539, in _open
    return self._call_chain(self.handle_open, 'unknown',
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 1417, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: s3>
[2022-10-18 13:22:18,113: INFO: stage_01_get_data]: 
********************
[2022-10-18 13:22:18,113: INFO: stage_01_get_data]: >>>>> stage stage 01 get data started <<<<<
[2022-10-18 13:22:18,121: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-10-18 13:22:18,121: INFO: common]: created directory at: data
[2022-10-18 13:22:18,122: INFO: stage_01_get_data]: Download started
[2022-10-18 13:22:41,915: INFO: stage_01_get_data]: Download completed
[2022-10-18 13:22:41,916: INFO: stage_01_get_data]: Download file is present at: data\data.xml
[2022-10-18 13:22:41,962: INFO: stage_01_get_data]: Download headers: x-amz-id-2: 3uY7gh3Ugtu3TuX/rOYDwHat+c5Gg4aP+Z1lrEAWrYP/zji5UNhiEvtC0fq0lehBuueC8z917as=
x-amz-request-id: 4JG5V9FSDRAH54BJ
Date: Tue, 18 Oct 2022 11:21:47 GMT
Last-Modified: Tue, 18 Oct 2022 00:30:29 GMT
ETag: "bf7eaa28ecc8e7af14695bc914c69427-3"
Accept-Ranges: bytes
Content-Type: text/xml
Server: AmazonS3
Content-Length: 37891850
Connection: close


[2022-10-18 13:22:41,963: INFO: stage_01_get_data]: >>>>> stage stage 01 get data completed!<<<<<

[2022-10-20 23:25:40,514: INFO: stage_01_get_data]: 
********************
[2022-10-20 23:25:40,514: INFO: stage_01_get_data]: >>>>> stage stage 01 get data started <<<<<
[2022-10-20 23:25:40,522: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-10-20 23:25:40,522: INFO: common]: created directory at: data
[2022-10-20 23:25:40,522: INFO: stage_01_get_data]: Download started
[2022-10-20 23:28:15,077: INFO: stage_01_get_data]: Download completed
[2022-10-20 23:28:15,078: INFO: stage_01_get_data]: Download file is present at: data\data.xml
[2022-10-20 23:28:15,117: INFO: stage_01_get_data]: Download headers: x-amz-id-2: +DbTiYrAyQ2E1ZHl6WFb46l22RWvl8Do3nGNfgVdLSYHZWmuZlJncvjj5T1hsIohD2NmxKjeYZDF0cCZym+slg==
x-amz-request-id: 6ZVPNKFF5A4TZ1ST
Date: Thu, 20 Oct 2022 21:25:05 GMT
Last-Modified: Tue, 18 Oct 2022 00:30:29 GMT
ETag: "bf7eaa28ecc8e7af14695bc914c69427-3"
Accept-Ranges: bytes
Content-Type: text/xml
Server: AmazonS3
Content-Length: 37891850
Connection: close


[2022-10-20 23:28:15,120: INFO: stage_01_get_data]: >>>>> stage stage 01 get data completed!<<<<<

[2022-10-20 23:29:56,882: INFO: stage_01_get_data]: 
********************
[2022-10-20 23:29:56,882: INFO: stage_01_get_data]: >>>>> stage stage 01 get data started <<<<<
[2022-10-20 23:29:56,886: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-10-20 23:29:56,886: INFO: common]: created directory at: data
[2022-10-20 23:29:56,886: INFO: stage_01_get_data]: Download started
[2022-10-20 23:31:31,840: INFO: stage_01_get_data]: Download completed
[2022-10-20 23:31:31,840: INFO: stage_01_get_data]: Download file is present at: data\data.xml
[2022-10-20 23:31:31,848: INFO: stage_01_get_data]: Download headers: x-amz-id-2: w2V7IQLe8oN6xQLuwNHXkW7VunXar4ucvPupo4AaH0Y3irqbvp0u7Blny8gFIYoyIzszI+9kF4kbS+vik1SnEQ==
x-amz-request-id: EZ8782Z27EA60ZZH
Date: Thu, 20 Oct 2022 21:29:21 GMT
Last-Modified: Tue, 18 Oct 2022 00:30:29 GMT
ETag: "bf7eaa28ecc8e7af14695bc914c69427-3"
Accept-Ranges: bytes
Content-Type: text/xml
Server: AmazonS3
Content-Length: 37891850
Connection: close


[2022-10-20 23:31:31,850: INFO: stage_01_get_data]: >>>>> stage stage 01 get data completed!<<<<<

[2022-10-20 23:39:41,576: INFO: stage_01_get_data]: 
********************
[2022-10-20 23:39:41,576: INFO: stage_01_get_data]: >>>>> stage stage 01 get data started <<<<<
[2022-10-20 23:39:41,577: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-10-20 23:39:41,577: INFO: common]: created directory at: data
[2022-10-20 23:39:41,577: INFO: stage_01_get_data]: Download started
[2022-10-20 23:41:17,741: INFO: stage_01_get_data]: Download completed
[2022-10-20 23:41:17,747: INFO: stage_01_get_data]: Download file is present at: data\data.xml
[2022-10-20 23:41:17,754: INFO: stage_01_get_data]: Download headers: x-amz-id-2: RGBr9kwZXlM+jGXV6xoIyskHZkOz9kF9ZI6g8YPiBtM1f9RRQbZIt+dFF3YJP1415pDYjlNQ750=
x-amz-request-id: 4M9TBTDJTT16A314
Date: Thu, 20 Oct 2022 21:39:06 GMT
Last-Modified: Tue, 18 Oct 2022 00:30:29 GMT
ETag: "bf7eaa28ecc8e7af14695bc914c69427-3"
Accept-Ranges: bytes
Content-Type: text/xml
Server: AmazonS3
Content-Length: 37891850
Connection: close


[2022-10-20 23:41:17,755: INFO: stage_01_get_data]: >>>>> stage stage 01 get data completed!<<<<<

[2022-10-20 23:44:27,130: INFO: stage_01_get_data]: 
********************
[2022-10-20 23:44:27,130: INFO: stage_01_get_data]: >>>>> stage stage 01 get data started <<<<<
[2022-10-20 23:44:27,131: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-10-20 23:44:27,131: INFO: common]: created directory at: data
[2022-10-20 23:44:27,131: INFO: stage_01_get_data]: Download started
[2022-10-20 23:49:44,937: INFO: stage_01_get_data]: Download completed
[2022-10-20 23:49:44,937: INFO: stage_01_get_data]: Download file is present at: data\data.xml
[2022-10-20 23:49:44,948: INFO: stage_01_get_data]: Download headers: x-amz-id-2: 5BK27Nlko1U7tfDzqlqvn//gUNN7JvSmq2nBhBTp73ncH8VNmzN5bRrb8Z2L8+lCOFHg8otRS5PICN86ovX8Yw==
x-amz-request-id: MVZNYJF8MS541S1X
Date: Thu, 20 Oct 2022 21:43:52 GMT
Last-Modified: Tue, 18 Oct 2022 00:30:29 GMT
ETag: "bf7eaa28ecc8e7af14695bc914c69427-3"
Accept-Ranges: bytes
Content-Type: text/xml
Server: AmazonS3
Content-Length: 37891850
Connection: close


[2022-10-20 23:49:44,948: INFO: stage_01_get_data]: >>>>> stage stage 01 get data completed!<<<<<

